package dev.livingkingdoms.profession.domain;

public enum BuildingCapability { HOUSING, FARMER_WORKPLACE, FOOD_PRODUCTION, ADMINISTRATION, GUARD_WORKPLACE, BLACKSMITH_WORKPLACE, STORAGE, DEFENSE_SUPPORT }
